# Generated by Django 4.1.13 on 2024-12-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('numero_punto', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('finalizado', 'Finalizado'), ('pendiente', 'Pendiente'), ('reservada', 'Reservada')], max_length=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('certificado', models.BooleanField(default=False)),
            ],
        ),
    ]
